# Generated by Django 5.0.6 on 2026-04-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("new_leads", models.IntegerField(default=0)),
                ("leads_won", models.IntegerField(default=0)),
                ("new_bookings", models.IntegerField(default=0)),
                ("new_contacts", models.IntegerField(default=0)),
                (
                    "revenue_earned",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["date"], name="analytics_d_date_ba81f3_idx")
                ],
            },
        ),
    ]
