# Generated by Django 5.0.6 on 2026-04-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0007_alter_contactsubmission_budget_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactsubmission",
            name="budget",
            field=models.CharField(
                blank=True,
                choices=[
                    ("under_50k", "Under ₹50K"),
                    ("50k_2lac", "₹50K–2L"),
                    ("2lac_5lac", "₹2L–5L"),
                    ("above_5lac", "Above ₹5L"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="contactsubmission",
            name="project_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mvp_development", "MVP Development"),
                    ("business_website", "Business Website"),
                    ("ai_web_app", "AI Web App"),
                    ("admin_dashboard", "Admin Dashboard"),
                    ("saas_platform", "SaaS Platform"),
                    ("api_backend", "API / Backend"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="portfolioproject",
            name="category",
            field=models.CharField(
                choices=[
                    ("mvp", "MVP Development"),
                    ("website", "Business Website"),
                    ("ai_app", "AI Web App"),
                    ("dashboard", "Admin Dashboard"),
                    ("saas", "SaaS Platform"),
                    ("api", "API & Backend"),
                    ("mobile", "Mobile App"),
                    ("ecommerce", "E-Commerce"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
