# Generated by Django 5.0.6 on 2026-07-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0009_contactsubmission_public_cont_project_23a3f2_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactsubmission",
            name="project_type",
            field=models.CharField(blank=True, default="other", max_length=100),
        ),
    ]
