# Generated by Django 5.0.6 on 2026-07-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0011_customerreview"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("excerpt", models.TextField(blank=True)),
                ("content", models.TextField()),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="blog/"),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("read_time_minutes", models.IntegerField(default=5)),
                ("views_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_published", "created_at"],
                        name="public_blog_is_publ_6c1fec_idx",
                    ),
                    models.Index(fields=["slug"], name="public_blog_slug_9866a1_idx"),
                ],
            },
        ),
    ]
