import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import prerender from '@prerenderer/rollup-plugin';
import PuppeteerRenderer from '@prerenderer/renderer-puppeteer';
import path from 'path';
import fs from 'fs';

// ─── EXTRACT ROUTES FROM SITEMAP ───
let prerenderRoutes = [
  '/', 
  '/about', 
  '/contact', 
  '/services', 
  '/portfolio', 
  '/pricing', 
  '/technologies', 
  '/faqs', 
  '/privacy-policy',
  '/blog'
];

try {
  // sitemap.xml is generated by Django prebuild step into public/sitemap.xml
  const sitemapPath = path.join(__dirname, 'public', 'sitemap.xml');
  if (fs.existsSync(sitemapPath)) {
    const sitemapContent = fs.readFileSync(sitemapPath, 'utf-8');
    // Extract all <loc> URLs
    const matches = sitemapContent.match(/<loc>(.*?)<\/loc>/g);
    if (matches) {
      const dynamicRoutes = matches.map(m => {
        const urlStr = m.replace('<loc>', '').replace('</loc>', '');
        const urlObj = new URL(urlStr);
        // Remove trailing slash for exact matching in React Router
        let pathname = urlObj.pathname;
        if (pathname !== '/' && pathname.endsWith('/')) {
          pathname = pathname.slice(0, -1);
        }
        return pathname;
      });
      // Merge and deduplicate
      prerenderRoutes = [...new Set([...prerenderRoutes, ...dynamicRoutes])];
    }
  }
} catch (err) {
  console.warn('Warning: Could not parse sitemap for prerender routes:', err.message);
}

export default defineConfig(async () => {
  let executablePath;
  let args = [];
  let headless = true;

  if (process.env.VERCEL || process.env.CI) {
    const chromium = (await import('@sparticuz/chromium')).default;
    executablePath = await chromium.executablePath();
    args = chromium.args;
    headless = chromium.headless;
  }

  return {
    plugins: [
      react(),
      prerender({
        staticDir: path.join(__dirname, 'dist'),
        renderer: new PuppeteerRenderer({
          renderAfterTime: 5000,
          maxConcurrentRoutes: 4,
          launchOptions: {
            executablePath,
            args,
            headless
          }
        }),
        routes: prerenderRoutes,
      })
    ],
    server: {
      allowedHosts: true,
      proxy: {
        '/api': 'http://localhost:8000',
        '/media': 'http://localhost:8000'
      }
    },
    build: {
      chunkSizeWarningLimit: 1000,
      rollupOptions: {
        output: {
          manualChunks: {
            vendor: ['react', 'react-dom', 'react-router-dom', 'react-helmet-async'],
            ui: ['framer-motion', 'lucide-react'],
            analytics: ['react-ga4'],
            auth: ['@clerk/clerk-react'],
            lenis: ['@studio-freight/lenis'],
          }
        }
      }
    }
  };
});

