import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import prerender from '@prerenderer/rollup-plugin';
import PuppeteerRenderer from '@prerenderer/renderer-puppeteer';
import path from 'path';
import fs from 'fs';

// ─── EXTRACT ROUTES FROM SITEMAP ───
let prerenderRoutes = [
  '/', 
  '/about', 
  '/contact', 
  '/services', 
  '/portfolio', 
  '/pricing', 
  '/technologies', 
  '/faqs', 
  '/privacy-policy',
  '/blog'
];

try {
  // sitemap.xml is generated by Django prebuild step into public/sitemap.xml
  const sitemapPath = path.join(__dirname, 'public', 'sitemap.xml');
  if (fs.existsSync(sitemapPath)) {
    const sitemapContent = fs.readFileSync(sitemapPath, 'utf-8');
    // Extract all <loc> URLs
    const matches = sitemapContent.match(/<loc>(.*?)<\/loc>/g);
    if (matches) {
      const dynamicRoutes = matches.map(m => {
        const urlStr = m.replace('<loc>', '').replace('</loc>', '');
        const urlObj = new URL(urlStr);
        // Remove trailing slash for exact matching in React Router
        let pathname = urlObj.pathname;
        if (pathname !== '/' && pathname.endsWith('/')) {
          pathname = pathname.slice(0, -1);
        }
        return pathname;
      });
      // Merge and deduplicate
      prerenderRoutes = [...new Set([...prerenderRoutes, ...dynamicRoutes])];
    }
  }
} catch (err) {
  console.warn('Warning: Could not parse sitemap for prerender routes:', err.message);
}

export default defineConfig({
  plugins: [
    react(),
    prerender({
      staticDir: path.join(__dirname, 'dist'),
      renderer: new PuppeteerRenderer({
        renderAfterTime: 5000,
        maxConcurrentRoutes: 4
      }),
      routes: prerenderRoutes,
    })
  ],
  server: {
    allowedHosts: true,
    proxy: {
      '/api': 'http://localhost:8000',
      '/media': 'http://localhost:8000'
    }
  },
  build: {
    chunkSizeWarningLimit: 1000,
    rollupOptions: {
      output: {
        manualChunks: {
          // Core React — always needed, smallest initial payload
          vendor: ['react', 'react-dom', 'react-router-dom', 'react-helmet-async'],
          // UI animation — framer-motion is large but used across all pages
          ui: ['framer-motion', 'lucide-react'],
          // Analytics — tiny, separate so it doesn't block rendering
          analytics: ['react-ga4'],
          // Auth — only needed on /dashboard and clerk-protected routes
          auth: ['@clerk/clerk-react'],
          // Smooth scroll — only used on public (non-admin) routes
          lenis: ['@studio-freight/lenis'],
        }
      }
    }
  }
});

