# Generated by Django 5.0.6 on 2026-04-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0005_sitecontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactsubmission",
            name="project_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mvp_development", "MVP Development"),
                    ("business_website", "Business Website"),
                    ("ai_web_app", "AI Web App"),
                    ("admin_dashboard", "Admin Dashboard"),
                    ("saas_platform", "SaaS Platform"),
                    ("api_backend", "API / Backend"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=100,
            ),
        ),
    ]
