# Generated by Django 5.0.6 on 2026-04-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0008_alter_contactsubmission_budget_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="contactsubmission",
            index=models.Index(
                fields=["project_type"], name="public_cont_project_23a3f2_idx"
            ),
        ),
    ]
