# Generated by Django 5.0.6 on 2026-07-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0010_alter_contactsubmission_project_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=255)),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                ("role", models.CharField(blank=True, max_length=255, null=True)),
                ("rating", models.IntegerField(default=5)),
                ("review_text", models.TextField()),
                ("is_approved", models.BooleanField(default=False)),
                ("avatar_url", models.URLField(blank=True, max_length=1000, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Customer Review",
                "verbose_name_plural": "Customer Reviews",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_approved"], name="public_cust_is_appr_249a4b_idx"
                    ),
                    models.Index(
                        fields=["rating"], name="public_cust_rating_bafe73_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="public_cust_created_df78ce_idx"
                    ),
                ],
            },
        ),
    ]
