# Generated by Django 5.0.6 on 2026-04-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_clerk_id", models.CharField(max_length=200)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("new_lead", "New Lead"),
                            ("new_booking", "New Booking"),
                            ("booking_cancelled", "Booking Cancelled"),
                            ("new_contact", "New Contact"),
                            ("lead_won", "Lead Won"),
                            ("follow_up_reminder", "Follow Up Reminder"),
                            ("project_update", "Project Update"),
                            ("project_file", "Project File Shared"),
                            ("invoice_created", "Invoice Created"),
                            ("invoice_updated", "Invoice Updated"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("data", models.JSONField(default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient_clerk_id", "is_read"],
                        name="notificatio_recipie_002e9e_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="notificatio_created_46ad24_idx"
                    ),
                ],
            },
        ),
    ]
