# Generated by Django 5.0.6 on 2026-04-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("key_hash", models.CharField(max_length=64, unique=True)),
                ("key_prefix", models.CharField(max_length=8)),
                ("owner_clerk_id", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("last_used_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner_clerk_id"], name="apikeys_api_owner_c_9e4476_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="apikeys_api_is_acti_67f3d4_idx"
                    ),
                ],
            },
        ),
    ]
