web: python manage.py collectstatic --noinput && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT --workers 2
worker: celery -A core worker --loglevel=info
beat: celery -A core beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
