# Generated by Django 5.0.6 on 2026-04-21 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0002_lead_crm_lead_status_2c1bc7_idx_and_more"),
        ("users", "0002_userprofile_users_userp_clerk_u_9beafc_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_url", models.URLField()),
                ("file_name", models.CharField(max_length=200)),
                ("file_type", models.CharField(max_length=50)),
                ("uploaded_by", models.CharField(max_length=200)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="crm.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("progress", models.IntegerField()),
                ("posted_by", models.CharField(max_length=200)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="crm.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("partial", "Partial"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                        ],
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="crm.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["invoice_number"], name="client_invo_invoice_fdd939_idx"
                    ),
                    models.Index(
                        fields=["status"], name="client_invo_status_9114fc_idx"
                    ),
                    models.Index(
                        fields=["due_date"], name="client_invo_due_dat_31b144_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectClientAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_assignments",
                        to="users.userprofile",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_assignments",
                        to="crm.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project"], name="client_proj_project_ea3ce7_idx"
                    ),
                    models.Index(
                        fields=["client"], name="client_proj_client__1f83bc_idx"
                    ),
                ],
                "unique_together": {("project", "client")},
            },
        ),
    ]
