# Generated by Django 5.0.6 on 2026-04-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioproject',
            name='image_url',
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
    ]
