# Generated by Django 5.0.6 on 2026-04-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0002_remove_portfolioproject_image_url_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="contactsubmission",
            index=models.Index(fields=["status"], name="public_cont_status_79ce44_idx"),
        ),
        migrations.AddIndex(
            model_name="contactsubmission",
            index=models.Index(
                fields=["submitted_at"], name="public_cont_submitt_01cb2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portfolioproject",
            index=models.Index(
                fields=["is_featured", "order"], name="public_port_is_feat_b4cb25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portfolioproject",
            index=models.Index(
                fields=["category"], name="public_port_categor_47f20f_idx"
            ),
        ),
    ]
