# Generated by Django 5.0.6 on 2026-04-21 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0003_contactsubmission_public_cont_status_79ce44_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactsubmission",
            name="budget",
            field=models.CharField(
                blank=True,
                choices=[
                    ("under_50k", "Under ₹50K"),
                    ("50k_2lac", "₹50K–2L"),
                    ("2lac_5lac", "₹2L–5L"),
                    ("above_5lac", "Above ₹5L"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="replied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="reply_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="service_interest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contact_submissions",
                to="public.serviceoffering",
            ),
        ),
        migrations.AlterField(
            model_name="contactsubmission",
            name="project_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name="contactsubmission",
            index=models.Index(
                fields=["priority"], name="public_cont_priorit_9b095d_idx"
            ),
        ),
    ]
