# Generated by Django 5.0.6 on 2026-04-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0006_alter_contactsubmission_project_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactsubmission",
            name="budget",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="contactsubmission",
            name="project_type",
            field=models.CharField(blank=True, default="other", max_length=100),
        ),
    ]
