# Generated by Django 5.0.6 on 2026-04-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["status"], name="crm_lead_status_2c1bc7_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["source"], name="crm_lead_source_0cf4cf_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["is_active", "created_at"], name="crm_lead_is_acti_9ac9d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["email"], name="crm_lead_email_57c21b_idx"),
        ),
    ]
