# Generated by Django 5.0.6 on 2026-04-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["clerk_user_id"], name="users_userp_clerk_u_9beafc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["email"], name="users_userp_email_98de9a_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["role"], name="users_userp_role_c31a7e_idx"),
        ),
    ]
