# Generated by Django 5.0.6 on 2026-04-21 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_alter_appointment_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="appointment",
            name="booking_app_date_19472d_idx",
        ),
        migrations.RenameIndex(
            model_name="appointment",
            new_name="booking_app_date_47b9d1_idx",
            old_name="booking_app_date_8ff220_idx",
        ),
    ]
