# Generated by Django 5.0.6 on 2026-04-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_remove_appointment_booking_app_date_19472d_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
