# Generated by Django 5.0.6 on 2026-04-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["clerk_user_id"], name="booking_app_clerk_u_fa0a4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["date", "time_slot"], name="booking_app_date_19472d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["status"], name="booking_app_status_513784_idx"),
        ),
    ]
