# Generated by Django 5.0.6 on 2026-04-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_appointment_booking_app_clerk_u_fa0a4e_idx_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={("date", "time_slot", "service")},
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["date", "time_slot", "service"],
                name="booking_app_date_8ff220_idx",
            ),
        ),
    ]
